return {
	"folke/snacks.nvim",
	opts = {
		-- --- Terminal ---
		terminal = { enabled = false }, -- Snacks terminal
	},
	-- 	keys = {
	-- 		-- --- TERMINAL ---
	-- 		{
	-- 			"<C-\\>",
	-- 			function()
	-- 				Snacks.terminal.toggle()
	-- 			end,
	-- 			desc = "Toggle Terminal",
	-- 			mode = { "n", "t" },
	-- 		},
	-- 		{
	-- 			"<leader>tt",
	-- 			function()
	-- 				Snacks.terminal.toggle()
	-- 			end,
	-- 			desc = "Toggle Terminal",
	-- 		},
	-- 		{
	-- 			"<leader>tf",
	-- 			function()
	-- 				Snacks.terminal.open(nil, { win = { position = "float" } })
	-- 			end,
	-- 			desc = "Toggle Terminal (Float)",
	-- 		},
	-- 		{
	-- 			"<leader>th",
	-- 			function()
	-- 				Snacks.terminal.open(nil, { win = { position = "bottom" } })
	-- 			end,
	-- 			desc = "Toggle Terminal (Bottom Split)",
	-- 		},
	-- 		{
	-- 			"<leader>tv",
	-- 			function()
	-- 				Snacks.terminal.open(nil, { win = { position = "right" } })
	-- 			end,
	-- 			desc = "Toggle Terminal (Right Split)",
	-- 		},
	-- 		{
	-- 			"<leader>tn",
	-- 			function()
	-- 				Snacks.terminal.open()
	-- 			end,
	-- 			desc = "New Terminal",
	-- 		},
	-- 		{
	-- 			"<leader>1",
	-- 			function()
	-- 				Snacks.terminal.toggle(nil, { count = 1 })
	-- 			end,
	-- 			desc = "Terminal 1",
	-- 		},
	-- 		{
	-- 			"<leader>2",
	-- 			function()
	-- 				Snacks.terminal.toggle(nil, { count = 2 })
	-- 			end,
	-- 			desc = "Terminal 2",
	-- 		},
	-- 		{
	-- 			"<leader>3",
	-- 			function()
	-- 				Snacks.terminal.toggle(nil, { count = 3 })
	-- 			end,
	-- 			desc = "Terminal 3",
	-- 		},
	-- 		{
	-- 			"<leader>4",
	-- 			function()
	-- 				Snacks.terminal.toggle(nil, { count = 4 })
	-- 			end,
	-- 			desc = "Terminal 4",
	-- 		},
	-- 		{
	-- 			"<leader>5",
	-- 			function()
	-- 				Snacks.terminal.toggle(nil, { count = 5 })
	-- 			end,
	-- 			desc = "Terminal 5",
	-- 		},
	-- 	},
}
